[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --strict-markers --disable-warnings"
testpaths = [
    "tests",
]
markers = [
    "unit: marks tests as unit tests (fast)",
    "integration: marks tests as integration tests (may be slow)",
    "cpp: marks tests that require C++ compilation",
    "windows: marks tests that require Windows-specific APIs",
    "slow: marks tests as slow (may take several seconds)",
]
python_files = [
    "test_*.py",
    "*_test.py",
]
python_classes = [
    "Test*",
]
python_functions = [
    "test_*",
]
junit_family = "xunit2"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
]
